### ISSUE TITLE
Python error when installing QFieldSync on macOS

### ISSUE THREAD

**Issue by timlinux** [opengisch/qfieldsync#101]
Hi Guys

I am getting this on install:

```
Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method  
TypeError: arguments did not match any overloaded call:   QLocale(): too many arguments   QLocale(str): argument 1 has unexpected type 'QVariant'   QLocale(QLocale.Language, country: QLocale.Country = QLocale.AnyCountry): argument 1 has unexpected type 'QVariant'   QLocale(QLocale): argument 1 has unexpected type 'QVariant'   QLocale(QLocale.Language, QLocale.Script, QLocale.Country): argument 1 has unexpected type 'QVariant' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/__init__.py", line 39, in classFactory
    return QFieldSync(iface)
  File "/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/qfield_sync.py", line 77, in __init__
    locale = QLocale(QSettings().value('locale/userLocale'))
TypeError: arguments did not match any overloaded call:
  QLocale(): too many arguments
  QLocale(str): argument 1 has unexpected type 'QVariant'
  QLocale(QLocale.Language, country: QLocale.Country = QLocale.AnyCountry): argument 1 has unexpected type 'QVariant'
  QLocale(QLocale): argument 1 has unexpected type 'QVariant'
  QLocale(QLocale.Language, QLocale.Script, QLocale.Country): argument 1 has unexpected type 'QVariant'
 Python version: 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]  QGIS version: 3.4.3-Madeira Madeira, exported  
Python Path:
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/karika
* /Applications/QGIS3.app/Contents/MacOS/../Resources/python
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
* /Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
* /Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SpeciesExplorer
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe_extras/parameters
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
* /Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe_extras
* .
* /Users/timlinux/Desktop
```

**Comment by m-kuhn** [comment]
Hi @timlinux 

Can you patch this file `/Users/timlinux/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/qfield_sync.py` with 

l```
ocale_str = QSettings().value('locale/userLocale')
if type(locale_str) == str:
    locale = QLocale(locale_str)
else:
    locale = QLocale()
```

**Comment by Doctor-Who** [comment]
Hi @m-kuhn 
I've got also that issue on Linux openSUSE and your patch allow me to activate the plugin on QGIS 3.6.1

**Comment by m-kuhn** [comment]
Thanks for the feedback @Doctor-Who pull request pending #112
