### ISSUE TITLE
cannot open project configuration menu

### ISSUE THREAD

**Issue by teeemmytim** [opengisch/qfieldsync#130]
so as the title says my issue is i cannot open the project cofiguration menu..
this is the error that i have been receiving.. I hope you can help me with this. thank you!

2019-11-22T14:05:33     WARNING    Traceback (most recent call last):
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 263, in show_project_configuration_dialog
              dlg = ProjectConfigurationDialog(self.iface, self.iface.mainWindow())
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 77, in __init__
              self.reloadProject()
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 139, in reloadProject
              unsupported_layers_text += '
' + '' + layer.name + ': ' + layer.warning
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\layer.py", line 139, in warning
              if self.layer.source().endswith('jp2', 'jpx'):
             TypeError: slice indices must be integers or None or have an __index__ method

**Comment by suricactus** [comment]
QGIS 3.4 is no longer supported. If are still experiencing the issue in more recent QGIS 3.x / QFieldSync 3.x/ QFieldSync 4.xBETA, please file a new issue.
