### ISSUE TITLE
Export big file (2.3Go) crash on windows but not on linux

### ISSUE THREAD

**Issue by pobsteta** [opengisch/qfieldsync#145]
Hi,

I have a big gpkg file with vector and multiple raster file (2.3 Go). On windows 8, export crash with python error :
```
2020-05-05T17:42:38     WARNING    Traceback (most recent call last):
              File "C:/Users/po76844/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 115, in package_project
              offline_convertor.convert()
              File "C:/Users/po76844/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\offline_converter.py", line 126, in convert
              copied_files = layer_source.copy(self.export_folder, copied_files)
              File "C:/Users/po76844/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\layer.py", line 199, in copy
              shutil.copy(os.path.join(source_path, basename + ext), dest_file)
              File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\shutil.py", line 241, in copy
              copyfile(src, dst, follow_symlinks=follow_symlinks)
              File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\shutil.py", line 122, in copyfile
              copyfileobj(fsrc, fdst)
              File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\shutil.py", line 82, in copyfileobj
              fdst.write(buf)
             PermissionError: [Errno 13] Permission denied
```

On linux it's ok.
@+

**Comment by m-kuhn** [comment]
Are you completely sure this is about the file size?

The error says "permission denied".

**Comment by suricactus** [comment]
Closed due to lack of feedback.
