### ISSUE TITLE
Error when syncing a project with WMS

### ISSUE THREAD

**Issue by pcav** [opengisch/QFieldSync#20]
```
IOError: [Errno 2] File o directory non esistente: u'crs=EPSG:4326&dpiMode=all&format=image/png&layers=CORINE_Land_Cover_2012&styles=&url=http://wms.skogoglandskap.no/cgi-bin/clc?' 
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/qfieldsync/dialogs/push_dialog.py", line 163, in push_project
    export_folder=export_folder)
  File "/home/paolo/.qgis2/python/plugins/qfieldsync/utils/export_offline_utils.py", line 59, in offline_convert
    handle_rasters(dataPath, raster_layers)
  File "/home/paolo/.qgis2/python/plugins/qfieldsync/utils/export_offline_utils.py", line 46, in handle_rasters
    shutil.copy(file_path, new_file_path)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] File o directory non esistente: u'crs=EPSG:4326&dpiMode=all&format=image/png&layers=CORINE_Land_Cover_2012&styles=&url=http://wms.skogoglandskap.no/cgi-bin/clc?'

```

**Comment by m-kuhn** [comment]
Do you have an idea which could be the layer triggering this error.

**Comment by pcav** [comment]
Yes:
http://wms.skogoglandskap.no/cgi-bin/clc?

**Comment by m-kuhn** [comment]
The latest version should deal nicely with WMS I think

**Comment by m-kuhn** [comment]
This should be resolved with the latest release. Please reopen if the issue persists.
