### ISSUE TITLE
Plugin crashes for filepaths containing special ch

### ISSUE THREAD

**Issue by saemiw** [opengisch/QFieldSync#22]
The plugin crashes when a file path (Export directory) is chosen that contains special characters ö, ä, ü,... 
![filepath](https://cloud.githubusercontent.com/assets/20398621/20712688/7f670e36-b645-11e6-8fd9-014d27a844c6.JPG)

QGIS produced the following python error:
2016-11-29T15:05:55	1	Traceback (most recent call last):
			  File "C:/Users/swe.VOGELWARTE/.qgis2/python/plugins\qfieldsync\dialogs\push_dialog.py", line 124, in push_project
			    self.do_post_offline_convert_action()
			  File "C:/Users/swe.VOGELWARTE/.qgis2/python/plugins\qfieldsync\dialogs\push_dialog.py", line 138, in do_post_offline_convert_action
			    result_folder='<a href="{folder}">{folder}</a>'.format(folder=export_folder)))
			UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 11: ordinal not in range(128)

by the way, I am using QGIS 2.18.0 and QFieldSync (v 0.8.5)

**Comment by m-kuhn** [comment]
Fixed in 0.8.6
