### ISSUE TITLE
QFieldSync crash after the QFC logout

### ISSUE THREAD

**Issue by suricactus** [opengisch/qfieldsync#239]
```
TypeError: cannot unpack non-iterable QNetworkReply object 
Traceback (most recent call last):
  File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/cloud_transferrer.py", line 470, in _on_logout_success
    self.abort_requests()
  File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/cloud_transferrer.py", line 410, in abort_requests
    for reply, _, _ in self.redirects:
TypeError: cannot unpack non-iterable QNetworkReply object
```

**Comment by suricactus** [comment]
Fixed with a75fca9dbabadb5f989da78b5c016e29e7d00f2b
