### ISSUE TITLE
How do I deploy the qfield_cloud branch for testing?

### ISSUE THREAD

**Issue by tomchadwin** [opengisch/qfieldsync#254]
Have you got a build process documented? I can see the branch relies on at least one submodule. Dropping them in manually still leaves import path errors.

**Comment by suricactus** [comment]
Hi Tom. Unfortunately the documentation of the build process is the code of the workflows only. Let me try to summarize what you need to do:

```
git clone git@github.com:opengisch/qfieldsync.git
cd qfieldsync
git checkout qfield_sync
git submodule update --init --recursive
qgis-plugin-ci package qfield_cloud
```

The last command will create a `qfieldsync.qfield_cloud.zip` file in the current directory, which can be installed from the plugin manager or uploaded to a private plugin repository. https://github.com/opengisch/qgis-plugin-ci

Hope it helps.

**Comment by m-kuhn** [comment]
There are also prepackaged versions available on https://github.com/opengisch/qfieldsync/releases

**Comment by tomchadwin** [comment]
Thanks, both!

> There are also prepackaged versions available on https://github.com/opengisch/qfieldsync/releases

Of that branch?

**Comment by m-kuhn** [comment]
Yep, the beta releases are (all?) off that branch

**Comment by m-kuhn** [comment]
For reference, here's the link to the latest version
https://github.com/opengisch/qfieldsync/releases/download/v4.0.0-beta6/qfieldsync.v4.0.0-beta6.zip

**Comment by tomchadwin** [comment]
Beta 6 gives me this on plugin load:

```
Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method 

ImportError: cannot import name 'LayerSource' from 'qfieldsync.libqfieldsync' (unknown location) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\__init__.py", line 40, in classFactory
    from qfieldsync.qfield_sync import QFieldSync
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 37, in 
    from qfieldsync.gui.package_dialog import PackageDialog
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 32, in 
    from qfieldsync.gui.project_configuration_dialog import ProjectConfigurationDialog
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\project_configuration_dialog.py", line 24, in 
    from qfieldsync.gui.project_configuration_widget import ProjectConfigurationWidget
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\project_configuration_widget.py", line 36, in 
    from qfieldsync.libqfieldsync import (
ImportError: cannot import name 'LayerSource' from 'qfieldsync.libqfieldsync' (unknown location)


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.3-Zürich Zürich, 735cc85be9 

Python Path:
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python
C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.18\apps\Python37
C:\PROGRA~1\QGIS3~1.18\apps\Python37\Scripts
C:\Program Files\QGIS 3.18\bin\python37.zip
C:\PROGRA~1\QGIS3~1.18\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib
C:\Program Files\QGIS 3.18\bin
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Chadwins!/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Chadwins!\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/CHADWI~1/AppData/Local/Temp/tmpua2tvlwl
```

**Comment by suricactus** [comment]
I can confirm all beta releases are on that branch. Can you please try on a clean QGIS profile without any other plugins? If you still have the error, please try the older beta 5? https://github.com/opengisch/qfieldsync/releases/download/v4.0.0-beta5/qfieldsync.v4.0.0-beta5.zip

**Comment by tomchadwin** [comment]
This coincided with delivery of a new laptop. New QGIS 3.18 install, installed beta 6 as only plugin, and it works. Thanks for the suggestion.
