### ISSUE TITLE
cannot load extension Qfielddsync - invoking classFactory()

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/qfieldsync#307]
Hello,

I cannot load anymore QFieldsync (latest version 4.0.0-BETA11) in QGIS 3.16. in order to publish my project to QFieldCloud.

Impossible de charger l'extension 'qfieldsync' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'typing_extensions' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\__init__.py", line 40, in classFactory
    from qfieldsync.qfield_sync import QFieldSync
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 32, in 
    from qfieldsync.core import Preferences
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\__init__.py", line 1, in 
    from .cloud_converter import CloudConverter  # NOQA
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_converter.py", line 28, in 
    from qfieldsync.libqfieldsync.layer import LayerSource
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\__init__.py", line 2, in 
    from .offline_converter import OfflineConverter
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 32, in 
    from typing_extensions import TypedDict
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'typing_extensions'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.16.4-Hannover Hannover, 654e76b3cb 

Chemin Python :
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/jdu/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by jpdupuy** [comment]
Hello,
I downloaded the latest QFIELDSYNC vesion 4.0.0-Beta-12
It now provokes a QGIS Crash when I try to open the layer properties.
I uninstalled QFIELDSYNC and now can open the layer properties without any crash.
Crash ID: c5db59a4c6e52b8a7290a70f4481b2819dc7774b


Stack Trace


QObject::parent :
QLayout::addChildWidget :
QStackedLayout::insertWidget :
QgsVectorLayerProperties::addPropertiesPageFactory :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363
