### ISSUE TITLE
QFieldSync : the project could not be converted into the export directory

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/qfieldsync#315]
Version 4.0.0.-Beta

Open my project, invoke qfieldcloud

![image](https://user-images.githubusercontent.com/72449015/133097209-4a58b247-2ccf-49a3-8ace-c26c9e1fc564.png)

Defined project details, then create
![image](https://user-images.githubusercontent.com/72449015/133097357-f2620eaf-a303-4255-aaf5-c67d447cf695.png)

Waiting for project conversion
![image](https://user-images.githubusercontent.com/72449015/133097464-d6a9e1dc-6030-4883-afbb-b0be8becc642.png)

Error message 
![image](https://user-images.githubusercontent.com/72449015/133097537-e15f7934-d9d2-4e16-b56d-4836cfebc893.png)

**Comment by jpdupuy** [comment]
version 4.0.0-beta12 + QGIS 3.16.4

**Comment by m-kuhn** [comment]
```

RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "C:/Users/Matthias Kuhn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_create_project_widget.py", line 367, in on_create_button_clicked
    self.cloudify_project()
  File "C:/Users/Matthias Kuhn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_create_project_widget.py", line 174, in cloudify_project
    cloud_convertor.convert()
  File "C:/Users/Matthias Kuhn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_converter.py", line 107, in convert
    ).format(layer.name()),
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

```

**Comment by suricactus** [comment]
This should be fixed in the new beta15.
