### ISSUE TITLE
Uncaught RuntimeError: The plugin QField Sync requires at least version 0.4.3 of the `qgis2compat` plugin. Please update it with the plugin manager.


### ISSUE THREAD

**Issue by gubuntu** [opengisch/qfieldsync#35]
Couldn't load plugin qfieldsync due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/usr/local/qgis-2.18/share/qgis/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/gavin/.qgis2/python/plugins/qfieldsync/__init__.py", line 56, in classFactory
    qgis2compat_version_check()
  File "/home/gavin/.qgis2/python/plugins/qfieldsync/__init__.py", line 48, in qgis2compat_version_check
    .format(plugin_name=plugin_name, qgis2compat_min_version=qgis2compat_min_version))
RuntimeError: The plugin QField Sync requires at least version 0.4.3 of the `qgis2compat` plugin. Please update it with the plugin manager.

```
qfieldsync 1.0.0, QGIS 2.18.3 on Linux 4.4.0-64-generic

**Comment by m-kuhn** [comment]
have you updated the qgis2compat plugin?
