### ISSUE TITLE
Pyhton error while testong latest beta

### ISSUE THREAD

**Issue by gioman** [opengisch/qfieldsync#350]
This appeared while putting off line a project

Traceback (most recent call last):
```
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 139, in package_project
    raise err
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 135, in package_project
    offline_convertor.convert()
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 137, in convert
    self._convert(project)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 317, in _convert
    raise Exception(
Exception: Error trying to convert layers to offline layers
```

Also notice that other times the export seems to work (no above error) but it gives others like:

`Failed to find layer with name "Distritos". QFieldSync will not package that layer.`

To note that the project does not have a layer that is just called "Distritos". As a result the off line project also contains layers that have been configured to be removed.

On 3.4 the export works as expected.

**Comment by suricactus** [comment]
Hey, @gioman , this error is due to QFieldSync gets failure status from `QgsOfflineEditing:;convertToOfflineProject`. Can you provide more information, a test project would be great?

**Comment by gioman** [comment]
> Can you provide more information, a test project would be great?

It was a test project and not sure if I have it still around, I will have a look as soon as I can.
