### ISSUE TITLE
Error when packed to QField

### ISSUE THREAD

**Issue by MrSeven590** [opengisch/qfieldsync#409]
`AssertionError 
Traceback (most recent call last):
  File "C:\Users/mr_se/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 144, in package_project
    offline_convertor = OfflineConverter(
  File "C:\Users/mr_se/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 115, in __init__
    assert self.area_of_interest_crs.isValid()
AssertionError

Python版本： 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS版本： 3.22.5-Białowieża Białowieża, c2723178 

Python路径：
D:/QGIS 3.22.5/apps/qgis-ltr/./python
C:/Users/mr_se/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/mr_se/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/QGIS 3.22.5/apps/qgis-ltr/./python/plugins
D:\QGIS 3.22.5\bin\python39.zip
D:\QGIS 3.22.5\apps\Python39\DLLs
D:\QGIS 3.22.5\apps\Python39\lib
D:\QGIS 3.22.5\bin
D:\QGIS 3.22.5\apps\Python39
D:\QGIS 3.22.5\apps\Python39\lib\site-packages
D:\QGIS 3.22.5\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
D:\QGIS 3.22.5\apps\Python39\lib\site-packages\win32
D:\QGIS 3.22.5\apps\Python39\lib\site-packages\win32\lib
D:\QGIS 3.22.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/mr_se/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/mr_se`

**Comment by m-kuhn** [comment]
What's the crs of your project?

**Comment by MrSeven590** [comment]
> What's the crs of your project?


Name：GCS_China_Geodetic_Coordinate_System_2000_3_Degree_GK_Zone_36
Units：meters
Method：Transverse Mercator
Celestial body：Earth
Reference：Static (relies on a datum which is plate-fixed)

**Comment by m-kuhn** [comment]
What version of qfieldsync are you running?

**Comment by MrSeven590** [comment]
> What version of qfieldsync are you running?

Installed version	4.0.0

**Comment by suricactus** [comment]
@MrSeven590 can you attach the project you are trying to package. Seems there is a specific errors with your CRS. A temporary workaround might be to configure the area of interest manually:

![image](https://user-images.githubusercontent.com/2820439/160376891-64835853-3d00-4e94-b532-04de0c6cba63.png)

**Comment by MrSeven590** [comment]
> @MrSeven590 can you attach the project you are trying to package. Seems there is a specific errors with your CRS. A temporary workaround might be to configure the area of interest manually:
> 
> ![image](https://user-images.githubusercontent.com/2820439/160376891-64835853-3d00-4e94-b532-04de0c6cba63.png)

thanks！The problem is solved！This is indeed a problem with the non-standard CRS
I provide a shp file for testin
[test.zip](https://github.com/opengisch/qfieldsync/files/8364131/test.zip)
g
