### ISSUE TITLE
Cannot change 'actions' for 'cable export'

### ISSUE THREAD

**Issue by thymaro** [opengisch/qfieldsync#425]
I have a project with several raster and vector layers (and one annotation layer).

When I try to configure the project for export, a python error occurs.

This is a screenshot of the configuration dialogue:

![grafik](https://user-images.githubusercontent.com/24420636/166913082-e8b5abd7-1373-4251-bda2-f08926ed199d.png)

In this screenshot, there are layers that show the action "copy".

- Without changing anything in the layer configuration, when I click the "Apply" button twice (once is not enough, it seems), the following error appears. 
- The error is also thrown when I change an action (from "copy" to "Keep existent", in my case) and the actions are reverted to their state before trying to apply the changes. 
- The error also appears when clicking "OK" and upon inspection of the layer properties, the values in the "Action" column are unchanged, i. e. still show "copy" instead of the desired "Keep existent (copy if missing)".

The error: 

```
An error has occurred while executing Python code: 

TypeError: 'function' object is not connected 
Traceback (most recent call last):
  File "C:\Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\beq/python/plugins\qfieldsync\gui\project_configuration_widget.py", line 197, in apply
    self.cloudLayersConfigWidget.apply()
  File "C:\Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\beq/python/plugins\qfieldsync\gui\layers_config_widget.py", line 284, in apply
    self.project.dirtySet.disconnect(self._on_dirtyset)
TypeError: 'function' object is not connected


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.6-Białowieża Białowieża, b6f33b1a 

Python Path:
C:\Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\beq/python/plugins\geo_sim_processing
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\beq/python
C:/Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\beq/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\beq/python
C:\Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\beq/python/plugins\qgis_resource_sharing
C:\Users\MyUserName\AppData\Roaming\QGIS\QGIS3\profiles\beq\python\plugins\qgis_resource_sharing
C:\Users\MyUserName\AppData\Roaming\QGIS\QGIS3\profiles\beq\python\plugins\qgis_resource_sharing\ext_libs
C:\Users\MyUserName\AppData\Roaming\QGIS\QGIS3\profiles\beq\python\plugins\QuickMultiAttributeEdit3/forms
C:/Project/Path/GIS
```

**Comment by suricactus** [comment]
This should be gone in 4.1.1 onwards.
