### ISSUE TITLE
Error when updating Qfield sync on QGIS 3.22

### ISSUE THREAD

**Issue by ponceta** [opengisch/qfieldsync#429]
I got this message today when updating qfieldsync.

No subsequent error, just for your information, feel free to close it.

Une erreur est survenue lors de l'éxécution du code Python: 

```
RuntimeError: wrapped C/C++ object of type QFieldCloudRootItem has been deleted 
Traceback (most recent call last):
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_browser_tree.py", line 81, in 
    lambda: self.refreshing_cloud_projects()
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_browser_tree.py", line 118, in refreshing_cloud_projects
    self.depopulate()
RuntimeError: wrapped C/C++ object of type QFieldCloudRootItem has been deleted


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.22.5-Białowieża Białowieża, c27231782f 
```

**Comment by m-kuhn** [comment]
This should be fixed with 4.5.0, please reopen if this persists after an upgrade. Thank you
