### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QgsRasterLayer has been deleted

### ISSUE THREAD

**Issue by gioman** [opengisch/qfieldsync#488]
```
Traceback (most recent call last):
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\layers_config_widget.py", line 93, in 
    lambda msg: self._on_message_bus_messaged(msg)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\layers_config_widget.py", line 274, in _on_message_bus_messaged
    layer_source.read_layer()
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\layer.py", line 101, in read_layer
    self._action = self.layer.customProperty("QFieldSync/action")
RuntimeError: wrapped C/C++ object of type QgsRasterLayer has been deleted
```

While working on a project with a delimited text layer and a layer from the quickmapservices plugin, and totally unrelated to qfield/sync.

QGIS 3.28 and the latest version of QFieldsync

**Comment by suricactus** [comment]
We play hide and seek with this exception for quite some time. Do you have a steps to reproduce or it happens occasionally?

**Comment by suricactus** [comment]
Thanks!

**Comment by suricactus** [comment]
@gioman I failed to reproduce your error. :( Can you provide the sample project that caused the error? Do you experince this in fresh QGIS too? Or in all projects?

**Comment by gioman** [comment]
@suricactus it is really a finicky scenario: now I got the error by loading a PostGIS layer and nothing else. The loaded layer had a style saved in the DB. After a single change in the D&D designer, clicking OK triggered the error.

**Comment by gioman** [comment]
Feedback already left.
