### ISSUE TITLE
Prepare data for Offline mode Python error

### ISSUE THREAD

**Issue by uprel** [opengisch/qfieldsync#49]
I get this error when I try to prepare one postgis point (single geom) layer for offline editing in qfield. And in exported folder there is only QGS project. Data should also be there, right?

```
2017-12-07T10:21:17	1	Traceback (most recent call last):
			  File "C:/Users/uros/.qgis2/python/plugins\qfieldsync\dialogs\package_dialog.py", line 113, in package_project
			    offline_convertor.convert()
			  File "C:/Users/uros/.qgis2/python/plugins\qfieldsync\core\offline_converter.py", line 131, in convert
			    self.project_configuration.offline_copy_only_aoi):
			TypeError: QgsOfflineEditing.convertToOfflineProject(QString, QString, QStringList): too many arguments
```

**Comment by m-kuhn** [comment]
Which QGIS version?

**Comment by uprel** [comment]
Hi,

That was on 2.14.11, I tried just now on 2.18.13 and it works. So you can close this one, thanks
Uroš
