### ISSUE TITLE
QGIS Project Properties dialog is broken after QFieldSync update

### ISSUE THREAD

**Issue by mblesius** [opengisch/qfieldsync#573]
After upgrading from QField Sync v4.9.0 to v4.9.1, the project properties dialog is broken. It appears, that the QField project properties dialog is integrated into another page in the project properties dialog and the sidebar for navigation on the left side is not visible.

![qfield_sync_properties_bug](https://github.com/opengisch/qfieldsync/assets/78353871/6f4b1e56-03d3-465d-99b3-d7d094aa5ecd)

### Version

<details open>
  <summary>QGIS-Version: 3.34.4. Prizren</summary>
  <br>

| QGIS-Version | 3.34.4-Prizren | QGIS code revision | [decd43dc](https://github.com/qgis/QGIS/commit/decd43dc) |
|---|---|---|---|
| Qt version | 5.15.3 | ||
| Python version | 3.9.18 | ||
| GDAL/OGR version | 3.8.4 | || 
| PROJ version | 9.3.1 | || 
| EPSG Registry database version | v10.098 (2023-11-24) | ||
| GEOS version | 3.12.1-CAPI-1.18.1 | ||
| SQLite version | 3.41.1 | ||
| PDAL version | 2.6.0 | || 
| PostgreSQL client version | 16.1 | ||
| SpatiaLite version | 5.1.0 | ||
| QWT version | 6.1.6 | ||
| QScintilla2 version | 2.13.4 | ||
| OS version | Windows 10 Version 2009 | ||

| Active Python plugins | Version |
|---|---|
| AnotherDXF2Shape | 1.3.1 |
| custom_titlebar | 1.0.0 |
| latlontools | 3.6.19 |
| mapswipetool_plugin | 1.2 |
| monokaiprospectrum | 1.0 |
| pathfinder | version 0.4.2 |
| pluginbuilder3 | 3.2.1 |
| plugin_reloader | 0.9.4 |
| project_colors_dock | 1.0.0 |
| QuickOSM | 2.2.3 |
| QuickWKT | 3.1 |
| quick_map_services | 0.19.34 |
| simplebutton | 0.1 |
| SpreadsheetLayers | 2.1.2 |
| db_manager | 0.1.20 |
| processing | 2.12.99 |
| qfieldsync | v4.9.1 |
| slyr_community | 5.0.0 |
</details>

### Steps to reproduce the issue

1. Start QGIS
2. Upgrade or install QField Sync v.4.9.1
3. Save the project
4. Open the project properties dialog

### Additional context

If there is no layer in the project, QField Sync throws a python error:
```
An error has occurred while executing Python code: 

AttributeError: 'ProjectConfiguration' object has no attribute 'force_auto_push' 
Traceback (most recent call last):
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\qfield_sync.py", line 63, in createWidget
    return ProjectConfigurationWidget(parent)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\project_configuration_widget.py", line 113, in __init__
    self.reloadProject()
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\project_configuration_widget.py", line 196, in reloadProject
    self.forceAutoPush.setChecked(self.__project_configuration.force_auto_push)
AttributeError: 'ProjectConfiguration' object has no attribute 'force_auto_push'


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.34.4-Prizren Prizren, decd43dc 

Python Path:
C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wea_test_areas
C:/PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.4\apps\grass\grass83\etc\python
C:\Users\user\Documents
C:\Program Files\QGIS 3.34.4\bin\python39.zip
C:\PROGRA~1\QGIS33~1.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib
C:\Program Files\QGIS 3.34.4\bin
C:\Users\user\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.4\apps\Python39
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:/temp/test/
```

**Comment by mblesius** [comment]
So, reloading the plugin actually fixed the error on my machine. I can't reproduce it now...
