### ISSUE TITLE
Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by TheDude005** [opengisch/qfieldsync#575]
I updated the plugin after updating Qgis today and now it is no longer working with a python issue.

Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'libqfieldsync.offliners' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/jordan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/__init__.py", line 48, in classFactory
    from qfieldsync.qfield_sync import QFieldSync
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jordan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/qfield_sync.py", line 42, in 
    from qfieldsync.gui.package_dialog import PackageDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jordan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/package_dialog.py", line 27, in 
    from libqfieldsync.offliners import QgisCoreOffliner
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'libqfieldsync.offliners'

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
QGIS version: 3.36.1-Maidenhead Maidenhead, 3e589453264

**Comment by suricactus** [comment]
Thank for the report Dude005!

Do you still have the error when you restart you QGIS or it is a one-time event?

**Comment by TheDude005** [comment]
Restarting again and reinitializing the plugin worked.  Thanks
