### ISSUE TITLE
Sync Issue With New Project

### ISSUE THREAD

**Issue by noah-hornak** [opengisch/qfieldsync#617]
Hi, I'm trying to get QGIS set up on my Linux machine and synced up with my Android mobile device using this plugin but I am unable to sync the project after creating a GeoPackage Layer on my desktop.

QFieldSync Plugin Version: [4.10.1]
QGIS Version: 3.26.3-Buenos Aires
Python Version: 3.8.10

Here are the steps I'm taking:
1. 'Layer'->'Create Layer'->'New GeoPackage Layer'. (This is a new file I'm creating)
![image](https://github.com/user-attachments/assets/85d3b1e3-46f1-49e3-abcf-1f9958490cba)
2. Save
3. Click the 'Synchronize Current Cloud Project' button in the toolbar (Blue Cloud with up/down arrows)
4. I'm presented with a never ending progress bar in the dialog box with the following Python Error being logged
![Screenshot from 2024-10-06 13-42-26](https://github.com/user-attachments/assets/f5489028-eff6-4c65-b1ac-d5cc56999a04)

2024-10-06T13:42:17     WARNING    Traceback (most recent call last):
              File "/home/noah/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/cloud_transfer_dialog.py", line 182, in showEvent
              self.show_project_compatibility_page()
              File "/home/noah/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/cloud_transfer_dialog.py", line 223, in show_project_compatibility_page
              feedback_table = CheckerFeedbackTable(feedback)
              File "/home/noah/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/checker_feedback_table.py", line 79, in __init__
              label.setTextFormat(Qt.MarkdownText)
             AttributeError: type object 'Qt' has no attribute 'MarkdownText'

Here are my QField Project Properties
![Screenshot from 2024-10-06 13-50-13](https://github.com/user-attachments/assets/7294ef4a-df4c-4ba9-b2e7-37793c0aa0ee)

I am only starting to try to learn GIS software starting today so this could be something very small I'm missing or doing wrong but I've tried for hours on fixing this with no success. Any help will be greatly appreciated!

**Comment by nirvn** [comment]
@noah-hornak  , what is the Qt version running on your system?

**Comment by noah-hornak** [comment]
@nirvn 5.12.8

**Comment by nirvn** [comment]
Ok. That'd be the problem, the Qt markdown formatting hinted at in the error logs was introduced in Qt 5.14.

What distro are you running?

**Comment by noah-hornak** [comment]
@nirvn Gotcha, I'm running Ubuntu 20.04.6 LTS

**Comment by osmtools** [comment]
Same here. I've tried to update Qt to 5.15 on Ubuntu 20.04.5 LTS without success. So I just commented out line 79 `label.setTextFormat(Qt.MarkdownText)` in `/home/[username]/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/checker_feedback_table.py` and it worked for me, because i don't need MarkdownText there.

**Comment by suricactus** [comment]
> Same here. I've tried to update Qt to 5.15 on Ubuntu 20.04.5 LTS without success. So I just commented out line 79 `label.setTextFormat(Qt.MarkdownText)` in `/home/[username]/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/checker_feedback_table.py` and it worked for me, because i don't need MarkdownText there.

Are you sure Qt picked up Qt 5.15? What is the output of calling `qVersion()` when you open the Python console within QGIS?

Anyways, I am closing this issue, as it is really a Qt<5.14 version issue, which is long time not supported and we are already discussing Qt 6 and QGIS.

**Comment by m-kuhn** [comment]
Ubuntu 20.04 is end of life in 2 months, I think itt's not worth adding compatibility code to the plugin at this time. I would suggest to update to a more recent distro.
