### ISSUE TITLE
Phyton Error

### ISSUE THREAD

**Issue by HerrRuin** [opengisch/qfieldsync#62]
Hello guys, 
trying to use the plugin, but always produce a python error when trying to configure the project for the plugin. I have absolutely no clue whats the problem is.

Thanks for help.

`2018-03-07T11:13:58	1	Traceback (most recent call last):
			  File "C:/Users/sboehm/.qgis2/python/plugins\qfieldsync\dialogs\package_dialog.py", line 94, in <lambda>
			    self.infoLabel.linkActivated.connect(lambda: self.show_settings())
			  File "C:/Users/sboehm/.qgis2/python/plugins\qfieldsync\dialogs\package_dialog.py", line 153, in show_settings
			    dlg = ProjectConfigurationDialog(self.iface, self.iface.mainWindow())
			  File "C:/Users/sboehm/.qgis2/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 56, in __init__
			    self.reloadProject()
			  File "C:/Users/sboehm/.qgis2/python/plugins\qfieldsync\dialogs\project_configuration_dialog.py", line 74, in reloadProject
			    for action, description in layer_source.available_actions:
			  File "C:/Users/sboehm/.qgis2/python/plugins\qfieldsync\core\layer.py", line 106, in available_actions
			    if self.is_file:
			  File "C:/Users/sboehm/.qgis2/python/plugins\qfieldsync\core\layer.py", line 97, in is_file
			    elif os.path.isfile(QgsDataSourceUri(self.layer.dataProvider().dataSourceUri()).database()):
			AttributeError: 'TileLayer' object has no attribute 'dataProvider'
			`

**Comment by m-kuhn** [comment]
Hello @HerrRuin, do you have a plugin layer active? E.g. openlayers?
