### ISSUE TITLE
BASE MAP

### ISSUE THREAD

**Issue by JAVIERSIG** [opengisch/qfieldsync#71]
Hello,
I start creating from openstreetmap, a map base and I see perfect in qgis, but when I try to export it with qfieldsync, it gives me flaws in those layers.

Thank you

**Comment by JAVIERSIG** [comment]
Hi @JAVIERSIG please note that this is not a support forum, but an issue tracker for bugs and feature requests.

The questions are very valid but should be redirected to one of the various support channels.

excuse me

**Comment by m-kuhn** [comment]
Can you copy/paste the "trazado de pila" in here?

**Comment by JAVIERSIG** [comment]
Ha ocurrido un error mientras se ejecutaba el código de Python: 

AttributeError: 'NoneType' object has no attribute 'copy' 
Traceback (most recent call last):
  File "C:/Users/JAVIE/.qgis2/python/plugins\qfieldsync\dialogs\package_dialog.py", line 116, in package_project
    offline_convertor.convert()
  File "C:/Users/JAVIE/.qgis2/python/plugins\qfieldsync\core\offline_converter.py", line 106, in convert
    self.project_configuration.base_map_mupp)
  File "C:/Users/JAVIE/.qgis2/python/plugins\qfieldsync\core\offline_converter.py", line 166, in createBaseMapLayer
    alg = processing.Processing.getAlgorithm('qfieldsync:basemap').getCopy()
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing\core\GeoAlgorithm.py", line 94, in getCopy
    newone = copy.copy(self)
AttributeError: 'NoneType' object has no attribute 'copy'


Versión de Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versión de QGIS: 2.18.19 Las Palmas, 3a17f72ba5 

Ruta de Python:
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python
C:/Users/JAVIE/.qgis2/python
C:/Users/JAVIE/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/JAVIE/.qgis2//python
C:/Users/JAVIE/.qgis2/python/plugins\go2streetview
C:\Users\JAVIE\.qgis2\python\plugins
C:\Users\JAVIE\.qgis2\python\plugins
C:/users/javie/appdata/local/temp/tmpnj7uzz

**Comment by JAVIERSIG** [comment]
This is M-Kuhn

**Comment by m-kuhn** [comment]
Interesting, can you go to the processing plugin options and check if there is an algorithm provider "qfieldsync" which you can enable?

**Comment by JAVIERSIG** [comment]
Hello M.;
I do not find anything about it. The complement itself does not give any other option.
I also check each and every one of the Qgis options in general; Even in the advanced menu and I do not find anything about it.

I only see, and I have to admit, that when I start qgis without any project, I get a UIC ruling, which I do not know if it will affect in any way.
I send the stack layout.

No se pudo cargar el complemento processing debido a un error al llamar a su método classFactory() 

ImportError: cannot import name uic 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing\__init__.py", line 37, in classFactory
    from processing.ProcessingPlugin import ProcessingPlugin
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing\ProcessingPlugin.py", line 38, in 
    from processing.gui.ProcessingToolbox import ProcessingToolbox
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 31, in 
    from qgis.PyQt import uic
ImportError: cannot import name uic

**Comment by m-kuhn** [comment]
Can you uninstall qgis2compat?

**Comment by JAVIERSIG** [comment]
![image](https://user-images.githubusercontent.com/17898868/39966345-a6b27b86-56aa-11e8-892a-3d27fd51f6e7.png)

![image](https://user-images.githubusercontent.com/17898868/39966347-b497cb5c-56aa-11e8-8239-3ed73f894f9b.png)


I already had it installed M.

(version problems do not think, right?)

**Comment by JAVIERSIG** [comment]
uninstall, sorry, just a moment

**Comment by JAVIERSIG** [comment]
uninstalled ,,, rebooted, tested, and this is the new stack plot:


IndexError: list index out of range
Traceback (most recent call last):
   File "C: /Users/JAVIE/.qgis2/python/plugins \ qfieldsync \ core \ offline_converter.py", line 189, in on_offline_editing_next_layer
     layer_name = self .__ offline_layers [layer_index - 1] .name ())
IndexError: list index out of range

**Comment by JAVIERSIG** [comment]
Just a moment.
Restart everything, and now, after removing qgis2compat ,,, if you have loaded the basemap. Two new ficehros have been created. basemap.gpkg and data sqlite.
You have made the correct import without any failure now.
That's it, on the mobile, the definition of the map looks fatal. I could try another one that was not openstreetmap ?, right?
